### ISSUE TITLE
Decryption Error for AEAD Ciphers

### ISSUE THREAD

**Issue by coderfox** [fsgmhoward/shadowsocks-py-mu#39] opened 2017-04-03 11:11 UTC
When using shadowsocks-openwrt 3.0.5 and shadowsocks-py-mu 3.3.0 and `chacha20-ietf-poly1305`, there happens to be a `Decryption Error` for every request.

How can I get detailed descriptions for the error? Have you tested AEAD ciphers? Which clients works?

Thanks for your kindly help.

**Comment by fsgmhoward** [comment] 2017-04-03 13:33
There is no AEAD support for early releases of ss-libev (which ss-openwrt bases on), which causes decryption error. I think this problem should have been fixed in version 3.0.1.

When I merge the commits, I found client ss-libev 3.0.0 does not work but 3.0.5 works properly (for both `shadowsocks/shadowsocks` and `fsgmhoward/shadowsocks-py-mu`, using cipher `aes-256-gcm` and `chacha20-ietf-chacha1305`).

I tested my server (`fsgmhoward/shadowsocks-py-mu`, version 3.3.0) again just now using chacha20-ietf-poly1305 as cipher and shadowsocks-c# @d7e5969 (newest commit) as client. Everything works great.

I think there is no problem with the server. The problem should comes from your client.

**Comment by coderfox** [comment] 2017-04-03 13:36
Thanks for your kind help.
Actually I am exactly using 3.0.5. So it must be my fault and sorry for the disturbing.
By the way, is there any possible methods to dump out the reason for decryption failures?

**Comment by fsgmhoward** [comment] 2017-04-03 14:22
Decryption failure should appear when an exception is thrown in the decryption process.
Sry about my previous post. I found that on some of my servers (not the one I used to test previously, `chacha20-ietf-poly1305` gives out decrypt failure as well.
I am investigating on this bug.

**Comment by coderfox** [comment] 2017-04-03 14:29
hhh

I have found my failure was due to unsuccessfully-updated packages. I think the log should distinguish between incorrect protocol and key incoordinance, which can be more friendly to find out GFW attacks.

Anyhow thanks for your help.

**Comment by fsgmhoward** [comment] 2017-04-03 14:33
- -
I just realised I failed because I forgot to change the cipher for my other profile in the client. This is not a bug.
Nvm I think I need more sleeping.

**Closed** 2017-04-03 14:33 UTC
Labels: bug
